### PR TITLE
Human-readable MACs/IPs

### PR DESCRIPTION
**Pull request by jue89**
Actually I'm too silly for reading this hex-coded supernode numbers. Can we change it without breaking the Internet / Freifunk?

### CODE REVIEW

**Comment by jue89** [comment]
Please double-check. I'm quite tiered right now ;)

**Comment by lemoer** [comment]
`sn{02,03,04,05,09}: Human-readable MACs` was applied as e21376c.

Further:
- Please split up ```sn{02,03,04,05,09}: Human-readable IPs``` in two commits (one for public, one for internal ips)
- You only changed the schema for the public IPs only for sn04 and sn05.. Why did you do this?

**Comment by jue89** [comment]
> You only changed the schema for the public IPs only for sn04 and sn05.. Why did you do this?
Well, the other IPs were human-readable. But yes, we should change them as well.

**Comment by jue89** [comment]
Ready to go ... hopefully.

After reading your comment, I realised I didn't do it the way you wanted. I split the PR up pre super node. So we can deploy it node after node and don't bother all users at once.

**Comment by jue89** [comment]
Push force again ^^

**Comment by lemoer** [comment]
`sn{02,03,04,05,09}: Updated internal IPv6 addr` is applied as 6d9a319b193fab0753860a8b6fadd4d805111ef5

Thanks for this, @jue89 I really like it :+1: 

@eaxi @1977er What do you say to the last commit?

**Comment by eaxi** [comment]
I like it. At the time we installed sn02 the first time, i indicated that we should make it so. Nice that it's now done.

**Comment by lemoer** [comment]
@eaxi Yes. I thought that you also would like this... IIRC, you told me, that hezner binds the IPv6 addresses to MAC addresses? Is this a problem here?

**Comment by eaxi** [comment]
@lemoer No theres no problem. The function which you can bind your /64 to an MAC-Address is for routed setups. But if you bind the /64 to the Host, it will be like an L2-Network, like the other IP-Adresses.

**Comment by lemoer** [comment]
The last commit is also applied. (47812b5)

@jue89 is there a special reason, why you left out sn09?

I'll leave this PR open until this is also done.

**Comment by jue89** [comment]
@lemoer: I'm blind.

**Comment by lemoer** [comment]
@1977er Do you also want to add the address to the ```mesh_fastd_listen_on``` variable?

**Comment by lemoer** [comment]
I'll close this, since it's already in the master branch.

**Pull request closed without merging**
